site_name: Лабораторная работа №3 — Гостиница (Django + DRF)
site_description: Отчет (одна страница) в формате MkDocs

theme:
  name: material
  language: ru

nav:
  - Отчет: index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
