site_name: Лабораторные работы по Web-программированию
site_description: Отчеты по всем лабораторным работам (Lab 1, Lab 2, Lab 3)
site_author: Абакунов Кирилл, группа K3340

docs_dir: docs

theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - Lab 1: lab1.md
  - Lab 2: lab2.md
  - Lab 3: lab3.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
